### ISSUE TITLE
model transform?

### ISSUE THREAD

**Issue by pgruenbacher** [jdupuy/opengl-framework#2]
If trying to apply a model transform to the isubd terrain (for scaling and whatnot) it seems to break the LOD calculations. Or at least does not behave as expected. Does the lod factor need to update along with the model scale, and if so, what do you think the math would be for that?

**Comment by jdupuy** [comment]
The algorithm can only support uniform scaling. So if you want to expose arbitrary model matrices (including non-uniform scaling), this code won't function unfortunately.

**Comment by pgruenbacher** [comment]
even with uniform scaling it didn't seem to work, but what ended up resolving the issue was setting things up so that during the lod compute, the camera view matrix was inverse transformed by the model transform. I.e. the compute operates on the 0,1 terrain quad with no scaling, but if the terrain is ultimately scaled by 1000, then the camera view matrix is scaled by 0.001 during the compute.

**Comment by pgruenbacher** [comment]
I can expound further if others run into this issue in the future.

**Comment by jdupuy** [comment]
Forgive me, my answer wasn't clear.
You're absolutely right: this code doesn't allow for scaling at all.
But the algorithm itself supports uniform scaling so this code can be extended to support it (I've done this before for another project). However, I don't plan to update this code in the near future as I have a much improved version in the pipes.

**Comment by zacharycarter** [comment]
@jdupuy - sorry for necroing this, but you mentioned that you have a much improved version in the pipes, and that this algo can handle uniform scaling. Is anything published on this improved version - or could you explain how you extended this example to support uniform scaling? I'm trying to figure out how to extend this example to support larger terrains.

**Comment by jdupuy** [comment]
@zacharycarter the new version is available here: https://github.com/jdupuy/LongestEdgeBisection2D

**Comment by zacharycarter** [comment]
@jdupuy - thanks! Checking that project out now!
