### ISSUE TITLE
missing triangles when camera moving ?

### ISSUE THREAD

**Issue by zhaijialong** [jdupuy/opengl-framework#3]
Hi,
Great terrain demo, thanks for the code. 
I noticed some random triangles will disappear when camera moving, what do you think is the reason for this ? and any ways to fix/improve this ?

**Comment by jdupuy** [comment]
Hi, 
You may notice such issues if you overflow the buffer that stores the triangles. You can try to increase the size of the buffer if this is too frequent for your use case.
